#!/bin/bash
# Generate simple app icons using ImageMagick (if available) or fallback

# Check if ImageMagick is available
if command -v convert &> /dev/null; then
    # Create 192x192 icon with book emoji style
    convert -size 192x192 xc:"#2563eb" -gravity center \
        -pointsize 120 -fill white -annotate +0+0 "📚" \
        icon-192.png
    
    # Create 512x512 icon
    convert -size 512x512 xc:"#2563eb" -gravity center \
        -pointsize 320 -fill white -annotate +0+0 "📚" \
        icon-512.png
    
    echo "Icons generated successfully using ImageMagick"
else
    echo "ImageMagick not found. Creating solid color placeholders..."
    # Fallback: create simple colored squares using base64 encoded minimal PNGs
    
    # 192x192 blue square (minimal PNG)
    echo "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAAsTAAALEwEAmpwYAAABL0lEQVR4nO3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOBXA8IAAUIcR6lrAAAAAElFTkSuQmCC" | base64 -d > icon-192.png
    
    # 512x512 blue square (minimal PNG)
    echo "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAAsTAAALEwEAmpwYAAABYklEQVR4nO3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOA1A1cAAiIsqLWUAAAAAElFTkSuQmCC" | base64 -d > icon-512.png
    
    echo "Placeholder icons created"
fi

echo "Icon files:"
ls -lh icon-*.png
